In [ ]:
#Question 1
def maxi(a,b,c):
  if a>b and a>c:
    l=a
  elif b>a and b>c:
    l=b
  elif c>a and c>b:
    l=c
  return (l)
one=int(input("Enter value 1:"))
two=int(input("Enter value 2:"))
three=int(input("Enter value 3:"))
anw=maxi(one,two,three)
print("Maximum value:",anw)


Enter value 1:56
Enter value 2:78
Enter value 3:90
Maximum value: 90


In [ ]:
#Question 2
def cir(ra):
  area=3.14*ra*ra
  return (area)
r=int(input("Enter the radius"))
ans=cir(r)
print("Area of circle:",ans)

Enter the radius2
Area of circle: 12.56


In [ ]:
#Question 3
def prime(p):
  if(p>1):
    for i in range(2,(p//2)+1):
      if(p%i==0):
        return False
      else:
        return True
p=int(input("Enter the number"))
an=prime(p)
print(an)



Enter the number7
True


In [ ]:
#Question 4
def pal(str):
  rev=str[::-1]
  if str==rev:
    return True
  else:
    return False
string=input("Enter the string:")
ans=pal(string)
print(ans)

Enter the string:malayalam
True


In [ ]:
#Question 5
def sum(list1):
  s=0
  for i in range(len(list1)):
    s=s+list1[i]
  return s
list11=[11,5,89,34,76]
answ=sum(list11)
print("Sum:",answ)

Sum: 215


In [ ]:
#Question 6
def avg(list2):
  sum=0
  for i in range(len(list2)):
    sum=sum+list2[i]
  l=len(list2)
  ag=sum/l
  return ag
list12=[23,56,67,12,3]
avge=avg(list12)
print("Average:",avge)

Average: 32.2


In [ ]:
#Question 7
def kl(li,k):
  li=sorted(li,reverse=True)
  return li[k-1]

li=[56,2,90,23,5]
v=2
value=kl(li,v)
print(v,"th largest element is",value)


2 th largest element is 56


In [ ]:
#Question 8
def sum(number):
  if number<10:
    return number
  else:
    return sum(sum(number //10) + number %10)
n1=12345
re=sum(n1)
print("Sum of digit",re)

Sum of digit 6


In [ ]:
#Question 9
def po(b,e):
  if(e==1):
    return b
  else:
    return (b*po(b,e-1))
ba=int(input("Enter the value of base:"))
ex=int(input("Enter the valye of exponent:"))
z=po(ba,ex)
print("Power of number",z)


Enter the value of base:2
Enter the valye of exponent:3
Power of number 8


In [ ]:
#Question 10
def g(m1,m2):
  if m1<m2:
    (m1,m2)=(m2,m1)
  while (m1 % m2!=0):
    (m1,m2)=(m2,m1%m2)
  return m2
ab=8
bc=12
res=g(8,12)
print("Gcd of",ab,"and" ,bc,"is",res)



Gcd of 8 and 12 is 4


In [ ]:
#Question 11
import numpy as np
id=np.arange(0,10)
id


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Question 12
v=np.arange(1,10)
twod=v.reshape(3,3)
twod



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Question 13
i=np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Question 14
a1=np.random.randn(10)
mean=np.mean(a1)
standard=np.std(a1)
print("mean=",mean)
print("standard deviation=",standard)

mean= 0.35673772955475425
standard deviation= 1.3596231003056278


In [ ]:
#Question 15
a11=np.arange(10,21)
e=a11[:5]
e

array([10, 11, 12, 13, 14])

In [ ]:
#Question 16
kl=np.arange(0,16)
vl=kl.reshape(4,4)
print(vl[1,:])

[4 5 6 7]


In [ ]:
#Question 17
one=np.arange(1,6)
two=np.arange(6,11)
st=np.vstack((one,two))
print(st)
add=one+two
print(add)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7  9 11 13 15]


In [ ]:
#Question 18
r1=np.random.rand(10)
r1[r1<0.5]=0
r1


array([0.9599072 , 0.        , 0.97156095, 0.6741278 , 0.9945591 ,
       0.        , 0.        , 0.        , 0.63517104, 0.        ])